# Generated by Django 5.2.5 on 2025-08-15 17:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_amenity_propertyimage_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(help_text='Payment reference number', max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent Payment'), ('security_deposit', 'Security Deposit'), ('other', 'Other Payment')], default='rent', max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'MPesa'), ('bank_card', 'Bank Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('months_paid_for', models.PositiveIntegerField(blank=True, help_text='Number of months this payment covers (1-6 months)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('rent_period_start', models.DateField(blank=True, null=True)),
                ('rent_period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property')),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.rentalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MPesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='MPesa registered phone number', max_length=15)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('paybill', 'Pay Bill'), ('buygoods', 'Buy Goods'), ('sendmoney', 'Send Money')], default='paybill', max_length=20)),
                ('mpesa_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_details', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='BankCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Last 4 digits of card', max_length=20)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover')], max_length=20)),
                ('expiry_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.PositiveIntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_zip', models.CharField(max_length=20)),
                ('billing_country', models.CharField(default='Kenya', max_length=100)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('cvv_verified', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card_details', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='properties.rentalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='payments_pa_tenant__13fdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rental_unit', 'payment_date'], name='payments_pa_rental__aaceed_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='payments_pa_status_3f89d4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='payments_pa_payment_93fd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['phone_number', 'mpesa_status'], name='payments_mp_phone_n_49eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['mpesa_receipt_number'], name='payments_mp_mpesa_r_b94743_idx'),
        ),
        migrations.AddIndex(
            model_name='bankcardpayment',
            index=models.Index(fields=['card_type', 'expiry_year'], name='payments_ba_card_ty_109000_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['tenant', 'is_paid'], name='payments_se_tenant__6fcbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['rental_unit', 'is_paid'], name='payments_se_rental__5ca248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securitydeposit',
            unique_together={('tenant', 'rental_unit')},
        ),
    ]
