# Generated by Django 5.2.5 on 2025-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="RentalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1br", "1 Bedroom"),
                            ("2br", "2 Bedroom"),
                            ("3br", "3 Bedroom"),
                            ("4br", "4+ Bedroom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_occupied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
