# Generated by Django 5.2.5 on 2025-08-14 18:21

import django.core.validators
import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=properties.models.property_image_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary image for property listing"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Properties"},
        ),
        migrations.AlterModelOptions(
            name="rentalunit",
            options={"ordering": ["property", "unit_number"]},
        ),
        migrations.RemoveField(
            model_name="rentalunit",
            name="is_occupied",
        ),
        migrations.RemoveField(
            model_name="rentalunit",
            name="monthly_rent",
        ),
        migrations.AddField(
            model_name="property",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="property",
            name="county",
            field=models.CharField(
                choices=[
                    ("nairobi", "Nairobi"),
                    ("mombasa", "Mombasa"),
                    ("kiambu", "Kiambu"),
                    ("nakuru", "Nakuru"),
                    ("machakos", "Machakos"),
                    ("kajiado", "Kajiado"),
                    ("kisumu", "Kisumu"),
                    ("uasin_gishu", "Uasin Gishu"),
                    ("meru", "Meru"),
                    ("nyeri", "Nyeri"),
                    ("murang'a", "Murang'a"),
                    ("kirinyaga", "Kirinyaga"),
                    ("embu", "Embu"),
                    ("kitui", "Kitui"),
                    ("makueni", "Makueni"),
                    ("other", "Other"),
                ],
                default="nairobi",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="property",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Property manager (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("townhouse", "Townhouse"),
                    ("studio", "Studio"),
                    ("bedsitter", "Bedsitter"),
                    ("maisonette", "Maisonette"),
                    ("bungalow", "Bungalow"),
                    ("commercial", "Commercial"),
                    ("office", "Office Space"),
                ],
                default=" ",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="town",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="current_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rented_units",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                help_text="Security deposit in KES",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="floor_area",
            field=models.PositiveIntegerField(
                blank=True, help_text="Floor area in square feet", null=True
            ),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="floor_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="lease_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="lease_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalunit",
            name="rent_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=10000,
                help_text="Monthly rent in KES",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rentalunit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("studio", "Studio"),
                    ("bedsitter", "Bedsitter"),
                    ("1br", "1 Bedroom"),
                    ("2br", "2 Bedroom"),
                    ("3br", "3 Bedroom"),
                    ("4br", "4+ Bedroom"),
                    ("maisonette", "Maisonette"),
                    ("penthouse", "Penthouse"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="rentalunit",
            index=models.Index(
                fields=["property", "is_available"],
                name="properties__propert_ee2a9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalunit",
            index=models.Index(
                fields=["unit_type"], name="properties__unit_ty_33dda5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalunit",
            index=models.Index(
                fields=["rent_amount"], name="properties__rent_am_95e000_idx"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="properties.amenity"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["county", "town"], name="properties__county_e91317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type"], name="properties__propert_5c7790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_active"], name="properties__is_acti_78cc81_idx"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "is_primary"], name="properties__propert_6e4e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "order"], name="properties__propert_94c164_idx"
            ),
        ),
    ]
