# Generated by Django 5.2.5 on 2025-08-15 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_amenity_propertyimage_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalunit',
            options={'ordering': ['property', 'floor_number', 'unit_number']},
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of floors (required for commercial properties)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='units_per_floor',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units per floor (required for commercial properties)', null=True),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, help_text='Floor number (required for commercial properties)', null=True),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='unit_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('4br', '4+ Bedroom'), ('maisonette', 'Maisonette'), ('penthouse', 'Penthouse'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('industrial', 'Industrial Space')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='rentalunit',
            index=models.Index(fields=['floor_number'], name='properties__floor_n_287b32_idx'),
        ),
    ]
