# Generated by Django 5.2.5 on 2025-08-16 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_rentalunit_options_property_number_of_floors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('intended_move_in_date', models.DateField(help_text='When the tenant intends to move in')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Security Deposit Paid'), ('confirmed', 'Reservation Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference from payment system', max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When the reservation expires if payment not made')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes from tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_reservations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.rentalunit')),
            ],
            options={
                'ordering': ['-reservation_date'],
                'indexes': [models.Index(fields=['status'], name='properties__status_7560de_idx'), models.Index(fields=['expires_at'], name='properties__expires_b3ea02_idx'), models.Index(fields=['tenant', 'status'], name='properties__tenant__be9311_idx')],
            },
        ),
    ]
